# name: Sync AI Application Rule incremental update
name: 增量更新

# 定义定时任务，每天凌晨2点运行（你可以根据需要调整时间）
on:
  workflow_dispatch:  # 允许通过 GitHub 页面手动触发工作流

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    # 拉取你的仓库代码
    - name: Checkout My Repo
      uses: actions/checkout@v3
      with:
        repository: hwangzhun/split-config
        path: my-repo

    # 设置 Python 环境
    - name: Set up Python
      uses: actions/setup-python@v4  # 使用官方的 Python 设置 action
      with:
        python-version: '3.12.x'  # 选择合适的 Python 版本

    # 安装依赖
    - name: install requests
      run: |
        cd my-repo/private\ rules # 切换到正确的目录
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    # 运行 main.py 脚本
    - name: Run main.py
      run: |
        cd my-repo/private\ rules # 切换到正确的目录
        python main.py  # 执行脚本
  

    # 提交并推送更改
    - name: Commit and Push Changes
      run: |
        cd my-repo
        git config user.name "GitHub Action"
        git config user.email "huangzhenmsn@hotmail.com"

        # 添加并提交新的规则
        git add rules
        git commit -m "例行更新" || echo "No changes to commit"  # 如果没有更改则跳过提交

        # 拉取最新的改动
        git pull origin master --rebase

        # 推送更改到远程仓库
        git push origin master
